project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - 404.qmd
    - slides/*
    - studies/*
    - git/*.qmd
    - quarto/*.qmd
    - tidyverse/*.qmd
    - about.qmd

website:
  title: "Methods in Corpus Linguistics"
  page-footer: "Methods in Corpus Linguistics --- Mariana Montes, 2022"
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Schedule & Overview
      - text: Studies
        menu:
          - studies/base.qmd
          - studies/genitive-alternation-retrieval.qmd
          - studies/genitive-alternation-analysis.qmd
          - studies/ca-trump-clinton.qmd
          - studies/register-analysis.qmd
      - text: Slides
        href: slides/index.qmd
      - text: Git cheatsheet
        href: git/cheatsheet.qmd
      - text: Assignments
        menu: 
          - git/assignment.qmd
          - quarto/crossref.qmd
          - tidyverse/tibbles.qmd
          - tidyverse/ggplot.qmd
          - quarto/markdown.qmd
          - quarto/citations.qmd
    search: true
format:
  html:
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: true
    code-link: true

execute:
  freeze: auto
  