project:
  type: website

website:
  title: "Methods in Corpus Linguistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Studies
        menu: 
          - base.qmd
          - genitive-alternation-retrieval.qmd
          - ca-trump-clinton.qmd
      - text: Slides
        menu: 
          - slides.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

