project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - 404.qmd
    - slides/intro.qmd
    - slides/init.qmd
    - slides/index.qmd
    - slides/contingency-tables.qmd
    - studies/base.qmd

website:
  title: "Methods in Corpus Linguistics"
  page-footer: "Methods in Corpus Linguistics --- Mariana Montes, 2022"
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Studies
        menu:
          - studies/base.qmd
      #     - studies/genitive-alternation-retrieval.qmd
      #     - studies/ca-trump-clinton.qmd
      - text: Slides
        href: slides/index.qmd
    search: true
format:
  html:
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: true
    code-link: true

execute:
  freeze: auto
  