project:
  type: website

website:
  title: "Methods in Corpus Linguistics"
  page-footer: "Methods in Corpus Linguistics --- Mariana Montes, 2022"
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Studies
        menu: 
          - studies/base.qmd
          - studies/genitive-alternation-retrieval.qmd
          - studies/ca-trump-clinton.qmd
      - text: Slides
        href: slides/index.qmd
    search: true
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-link: true

