---
title: "Citations in Quarto"
author: "Mariana Montes"
subtitle: "Sixth assignment"
number-sections: true
bibliography: citations.bib
csl: unified-style-sheet-for-linguistics.csl
---

The goal of this assignment is to practice introducing academic citations in a Quarto document.

# Instructions

1. Create a branch for the assignment, e.g. `citations`. You will work here and only move your changes to `main` if and when you want to submit.

1. Create a Quarto document (don't forget to remove its content!).

1. Write a short text with different kinds of citations, as exemplified in @sec-cite: lists of authors, author name integrated in the text, with page numbers...

    a. Include at least one block quote, even if ficticious.^[This is by no means a requirement in the final paper, just for the assignment.]
    
    b. If necessary (if it isn't printed automatically), add a "References" title at the end of your document.
    
    c. You can use [the bibliography file used here](https://raw.githubusercontent.com/mclm2022/mclm2022.github.io/main/quarto/citations.bib), but if you already have a list of sources for your paper, I would recommend trying to create the BibTeX file with them and using that.

1. Render your Quarto document into the output of your choice (word, html, pdf...).

1. Stage and commit all the relevant files (see [Cheatsheet](../git/cheatsheet.qmd#daily-workflow) if you don't remember how).

1. Merge the changes into your `main` branch (see [Cheatsheet](../git/cheatsheet.qmd#work-with-branches)).

1. Push the changes to the remote.

1. Send me an e-mail so I check if it went ok (I will not check your repository if you don't inform me).

# How to cite in Quarto {#sec-cite}

::: callout-warning
All the examples in this document are **fake citations**.
:::

I do recommend to keep at hand the [documentation](https://quarto.org/docs/authoring/footnotes-and-citations.html#citations) on citations in Quarto. The main idea is that a cited work is indicated with **an `@` followed by the citation key**. For a citation key "levshina_2015" and the citation style of the Unified Stylesheet for Linguistics:

Text in Quarto | Output
----- | -----
`@levshina_2015` | @levshina_2015
`@levshina_2015 [345]` | @levshina_2015 [345]
`[@levshina_2015]` | [@levshina_2015]
`[@levshina_2015 345]` | [@levshina_2015 345].

## Multiple works

Multiple works can be cited next to each other by separating them with a semicolon:

```md
The present document illustrates how to cite different works
[@evert_2009; @evert_2004; @mcenery.etal_2010].
As @levshina_2015 and @levshina.etal_2014 suggest,
this is just a fake example.
```

The present document illustrates how to cite different works [@evert_2009; @evert_2004; @mcenery.etal_2010]. As @levshina_2015 and @levshina.etal_2014 suggest, this is just a fake example.

## Quotes

Short quotes are simply surrounded by double quotation marks with the source and page number in parenthesis next to it: "This is a great example" [@montes_2022 1].

Block quotes are generated by preceding the text with a ">", without quotation marks.

```md
There is but one way of saying this:

> A long quote can be an effective way of conveying a uniquely phrased statement
that is too long to be inserted in the middle of a sentence. However, please be
advised and do not abuse of it. The text, after all, has to be your own.
[@montes_2022 2]
```

There is but one way of saying this:

> A long quote can be an effective way of conveying a uniquely phrased statement that is too long to be inserted in the middle of a sentence. However, please be advised and do not abuse of it. The text, after all, has to be your own. [@montes_2022 2]

# BibTeX and CSL

In order to provide the bibliographical information that Quarto needs, you need a BibTeX file, like [citations.bib used here](https://raw.githubusercontent.com/mclm2022/mclm2022.github.io/main/quarto/citations.bib). The filename should be indicated in the `bibliography` field of the metadata YAML:

```yml
title: "Title of my document"
author: "My name and surname"
bibliography: citations.bib
```

There are different ways of obtaining a BibTeX file. If you use [Zotero](https://www.zotero.org/), you can export any group of entries as a BibTeX file. If you add the [Better BibTeX](https://retorque.re/zotero-better-bibtex/) extension, you can keep such file updated, e.g. you export a collection, and every time you add or change something in the collection, your file will change accordingly. Better BibTeX also helps you define a template for your citation key, which otherwise can be very convoluted and hard to remember; you can read [this blogpost](https://marianamontes.netlify.app/post/obsidian-and-zotero/) for an example.^[You might also be interested in exploring [the `{rbbt}` package.](https://github.com/paleolimbot/rbbt)]

A citation style is coded in a [CSL file (Citation Style Language)](https://docs.citationstyles.org/en/stable/primer.html#what-is-csl). If you don't want to use Quarto's default style, you may provide another by adding a `csl` field in the metadata YAML, as is done in this document. The value should be the path to [a .csl file](https://raw.githubusercontent.com/mclm2022/mclm2022.github.io/main/quarto/unified-style-sheet-for-linguistics.csl), which you can download from the [Zotero CSL repository](https://www.zotero.org/styles) or even create/modify with a [Visual Editor](https://editor.citationstyles.org/visualEditor/).

```yml
title: "Title of my document"
author: "My name and surname"
bibliography: citations.bib
csl: unified-style-sheet-for-linguistics.csl
```

For both the assignment and the final paper, you are free to choose the stylesheet that you prefer.

# Git workflow {#sec-git}

```bash
git status # check that you're on main, nothing to commit...
git branch citations
git checkout citations
# work on your .qmd file, render
git status # check everything is fine
git add .
git commit -m "practice with citations"
git checkout main
git status # check everything is fine. New files should not be there
git merge citations
# Now the .qmd file, the rendered file and the help files should be present
git push
# and send me a message!
```
