{
  "hash": "d5cbc04182adf24a3bff22ca3da95909",
  "result": {
    "markdown": "---\ntitle: \"Contingency tables\"\nsubtitle: \"Methods of Corpus Linguistics\"\nauthor: \"Mariana Montes\"\nformat:\n  revealjs:\n    preview-links: auto\n    multiplex: true\nexecute:\n  echo: true\n---\n\n\n\n\n## Outline\n\n\n- Hot example \n- Observed frequencies \n- Expected frequencies \n- Target and reference contexts \n- Summing up \n\n\n# Hot example\n\n## Set up data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(mclm)\ncorpus_folder <- here::here(\"studies\", \"_corpora\", \"brown\")\nbrown_fnames <- get_fnames(corpus_folder) %>% keep_re(\"/c[a-z]\")\nflist <- freqlist(brown_fnames, re_token_splitter = re(\"\\\\s+\"))\nprint(flist, n = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFrequency list (types in list: 63517, tokens in list: 1162192)\nrank   type abs_freq nrm_freq\n---- ------ -------- --------\n   1 the/at    69013  593.818\n   2    ,/,    58153  500.373\n   3    ./.    48812  419.999\n   4  of/in    35028  301.396\n   5 and/cc    28542  245.588\n...\n```\n:::\n:::\n\n\n::: {.footer}\nHot example\n:::\n\n## Frequency of *hot*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflist %>% keep_re(\"^hot/\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFrequency list (types in list: 3, tokens in list: 130)\n<total number of tokens: 1162192>\nrank orig_rank      type abs_freq nrm_freq\n---- --------- --------- -------- --------\n   1       805    hot/jj      123    1.058\n   2     14852 hot/jj-tl        5    0.043\n   3     28147 hot/jj-hl        2    0.017\n```\n:::\n:::\n\n\n<!-- TODO transform corpus so that only the first two items in the POS tag show up? -->\n\n::: {.footer}\nHot example\n:::\n\n## Concordance of *hot* {auto-animate=TRUE}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhot <- conc(brown_fnames, \"\\\\bhot/jj\")\nhot\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nConcordance-based data frame (number of observations: 118)\nidx                             left|match |right                           \n  1 .../-- After/in a/at long/jj ,/,|hot/jj|controversy/nn ,/, Miller/np-...\n  2 ...$ Dave/np Mills/np in/in a/at|hot/jj|duel/nn in/in 1.10.1/cd ./. K...\n  3 ...opped/vbd this/dt suddenly/rb|hot/jj|potato/nn in/in a/at very/ql ...\n  4 ...wps got/vbd off/rp to/in a/at|hot/jj|start/nn and/cc made/vbd a/at...\n  5 .../at cup/nn of/in steaming/vbg|hot/jj|coffee/nn awaiting/vbg him/pp...\n  6 ...A/at measure/nn of/in how/wrb|hot/jj|the/at stock/nn was/bedz ,/, ...\n  7 ...oods/nns-tl issue/nn was/bedz|hot/jj|long/rb before/cs it/pps was/...\n  8 ...ock/nn issue/vb such/abl a/at|hot/jj|one/cd ?/. ?/. The/at answer/...\n  9 ... Foods/nns-tl stock/nn the/at|hot/jj|issue/nn that/cs it/pps was/b...\n 10 ..., introduced/vbd the/at ``/``|hot/jj|dog/nn ''/'' and/cc paved/vbd...\n 11 ...g/vbg temperatures/nns and/cc|hot/jj|summer/nn pavements/nns are/b...\n 12 ...der/rbr ./. An/at ordinary/jj|hot/jj|bath/nn or/cc shower/nn will/...\n 13 ...smell/nn and/cc feel/nn of/in|hot/jj|,/, wet/jj woolen/jj sleeves/...\n 14 ...ns ./. No/at matter/nn how/ql|hot/jj|the/at day/nn ,/, they/ppss a...\n 15 ... who/wps was/bedz blowing/vbg|hot/jj|and/cc cold/jj ,/, exalting/v...\n 16 ...der/in sunny/jj skies/nns ,/,|hot/jj|sun/nn ,/, and/cc a/at fresh/...\n 17 ...nd/vb the/at summer/nn too/ql|hot/jj|for/in comfort/nn ./. And/cc ...\n 18 ...n't/doz* mean/vb that/cs a/at|hot/jj|rodder/nn must/md necessarily...\n 19 ...ctive/jj and/cc successful/jj|hot/jj|rodder/nn for/in years/nns wi...\n 20 ...d/vbn to/in its/pp$ normal/jj|hot/jj|operating/vbg pressure/nn and...\n 21 ... rated/vbn at/in a/at very/ql|hot/jj|2,460/cd fps/nn ,/, and/cc it...\n 22 ...napkins/nns that/wps kept/vbd|hot/jj|a/at platter/nn of/in oyster/...\n 23 ...nn that/wps kept/vbd them/ppo|hot/jj|when/wrb served/vbn --/-- was...\n 24 ...n ./. Heat/vb and/cc serve/vb|hot/jj|on/in toast/nn ./. The/at ome...\n 25 ...f/cs they/ppss are/ber too/ql|hot/jj|,/, and/cc to/to stop/vb flam...\n 26 ...nns ./. And/cc lots/nns of/in|hot/jj|pads/nns !/. !/. Do/do keep/v...\n 27 .../nn chilled/vbn or/cc soup/nn|hot/jj|./. Be/be sure/jj to/to get/v...\n 28 ...e/at chili/nn and/cc kraut/nn|hot/jj|with/in the/at franks/nns ./....\n 29 ...p$ daytime/jj naps/nns and/cc|hot/jj|meals/nns ,/, and/cc be/be pu...\n 30 ...shed/vbn and/cc free/jj of/in|hot/jj|weather/nn nerves/nns ./. You...\n...\n...\n\nThis data frame has 6 columns:\n   column\n1 glob_id\n2      id\n3  source\n4    left\n5   match\n6   right\n```\n:::\n:::\n\n\n::: {.footer}\nHot example\n:::\n\n## Concordance of *hot* {auto-animate=TRUE}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhot %>% \n  arrange(right)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nConcordance-based data frame (number of observations: 118)\nidx                             left|match |right                           \n  1 ...t was/bedz the/at word/nn ,/,|hot/jj|!/. !/. Hair/nn like/cs a/at ...\n  2 .../vbz in/in the/at long/jj (/(|hot/jj|)/) run/nn to/to take/vb good...\n  3 ...f/cs they/ppss are/ber too/ql|hot/jj|,/, and/cc to/to stop/vb flam...\n  4 ...d/cc the/at dice/nns were/bed|hot/jj|,/, but/cc he/pps couldn't/md...\n  5 ...pps had/hvd been/ben still/rb|hot/jj|,/, she/pps might/md even/rb ...\n  6 ...e/pps felt/vbd cold/jj and/cc|hot/jj|,/, sticky/jj and/cc chilly/j...\n  7 ...ed/vbn on/in sensation/nn (/(|hot/jj|,/, sweet/jj ,/, bitter/jj ,/...\n  8 ...dz unusually/rb dry/jj and/cc|hot/jj|,/, the/at spring/nn produced...\n  9 ...smell/nn and/cc feel/nn of/in|hot/jj|,/, wet/jj woolen/jj sleeves/...\n 10 .../nn chilled/vbn or/cc soup/nn|hot/jj|./. Be/be sure/jj to/to get/v...\n 11 ...n and/cc felt/vbd a/at bit/nn|hot/jj|./. He/pps stayed/vbd home/nr...\n 12 ...d away/rb ./. It/pps was/bedz|hot/jj|./. The/at dogs/nns were/bed ...\n 13 ...and/cc the/at sun/nn was/bedz|hot/jj|./. The/at new/jj Riverside/n...\n 14 ... rated/vbn at/in a/at very/ql|hot/jj|2,460/cd fps/nn ,/, and/cc it...\n 15 ...napkins/nns that/wps kept/vbd|hot/jj|a/at platter/nn of/in oyster/...\n 16 ...vbd around/rb ,/, suddenly/rb|hot/jj|all/ql over/rp ,/, finding/vb...\n 17 ... who/wps was/bedz blowing/vbg|hot/jj|and/cc cold/jj ,/, exalting/v...\n 18 ...onal/jj wars/nns ,/, both/abx|hot/jj|and/cc cold/jj ./. In/in ever...\n 19 .... His/pp$ prescription/nn :/:|hot/jj|and/cc cold/jj compresses/nns...\n 20 ...heated/jj in/in winter/nn ,/,|hot/jj|and/cc damp/jj under/in the/a...\n 21 .../cs your/pp$ blood/nn got/vbd|hot/jj|and/cc danced/vbd with/in the...\n 22 .../. The/at theatre/nn was/bedz|hot/jj|and/cc they/ppss were/bed dru...\n 23 ...The/at sun/nn ,/, blazing/vbg|hot/jj|as/cs prophesied/vbn ,/, was/...\n 24 ...rb it/pps was/bedz already/rb|hot/jj|at/in 7:30/cd A.M./rb ,/, and...\n 25 ...d out/rp pink/jj from/in a/at|hot/jj|bath/nn ,/, and/cc I/ppss gav...\n 26 ...der/rbr ./. An/at ordinary/jj|hot/jj|bath/nn or/cc shower/nn will/...\n 27 ...at drifting/vbg odor/nn of/in|hot/jj|biscuits/nns ./. The/at old/j...\n 28 ...pss want/vb to/to buy/vb a/at|hot/jj|Bodhisattva/np ./. Additional...\n 29 ...t/nn of/in Mrs./np Fogg's/np$|hot/jj|broth/nn before/cs starting/v...\n 30 .../nn and/cc wiping/vbg his/pp$|hot/jj|brow/nn ./. It/pps may/md app...\n...\n...\n\nThis data frame has 6 columns:\n   column\n1 glob_id\n2      id\n3  source\n4    left\n5   match\n6   right\n```\n:::\n:::\n\n\n::: {.footer}\nHot example\n:::\n\n## Concordance of *hot* {auto-animate=TRUE}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhot %>% \n  arrange(right) %>% \n  print_kwic(from = 25, n = 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nidx                             left|match |right                           \n...\n 25 ...d out/rp pink/jj from/in a/at|hot/jj|bath/nn ,/, and/cc I/ppss gav...\n 26 ...der/rbr ./. An/at ordinary/jj|hot/jj|bath/nn or/cc shower/nn will/...\n 27 ...at drifting/vbg odor/nn of/in|hot/jj|biscuits/nns ./. The/at old/j...\n 28 ...pss want/vb to/to buy/vb a/at|hot/jj|Bodhisattva/np ./. Additional...\n 29 ...t/nn of/in Mrs./np Fogg's/np$|hot/jj|broth/nn before/cs starting/v...\n 30 .../nn and/cc wiping/vbg his/pp$|hot/jj|brow/nn ./. It/pps may/md app...\n 31 ...eakfast/nn of/in fruit/nn ,/,|hot/jj|cereal/nn ,/, milk/nn ,/, hon...\n 32 ...sed/vbd to/to like/vb any/dti|hot/jj|cereal/nn ,/, now/rb that's/d...\n 33 .../nns they/ppss miss/vb the/at|hot/jj|cereal/nn ./. The/at school/n...\n 34 ...to/to come/vb down/rp with/in|hot/jj|chills/nns and/cc puzzling/jj...\n 35 ... sprinkled/vbd sugar/nn on/in|hot/jj|coals/nns and/cc held/vbd the...\n 36 ...t nonexistent/jj cup/nn of/in|hot/jj|coffee/nn ,/, and/cc that/cs ...\n 37 ...h/nn for/in a/at cup/nn of/in|hot/jj|coffee/nn ./. They/ppss are/b...\n 38 .../at cup/nn of/in steaming/vbg|hot/jj|coffee/nn awaiting/vbg him/pp...\n 39 ...n boiled/vbn ,/, applying/vbg|hot/jj|compresses/nns throughout/in ...\n...\n```\n:::\n:::\n\n\n::: {.footer}\nHot example\n:::\n\n## Co-occurrences with *hot*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhot_cooc <- surf_cooc(brown_fnames, \"^hot/jj\", re_token_splitter = \"\\\\s+\")\n```\n:::\n\n\n<br>\n\n:::: {.columns}\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(hot_cooc$target_freqlist, 7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFrequency list (types in list: 7, tokens in list: 226)\n<total number of tokens: 777>\nrank orig_rank   type abs_freq nrm_freq\n---- --------- ------ -------- --------\n   1         1    ,/,       49  630.631\n   2         2 the/at       39  501.931\n   3         3    ./.       38  489.060\n   4         4 and/cc       36  463.320\n   5         5   a/at       28  360.360\n   6         6  of/in       21  270.270\n   7         7  in/in       15  193.050\n```\n:::\n:::\n\n\n:::\n\n::: {.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(hot_cooc$ref_freqlist, 7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFrequency list (types in list: 7, tokens in list: 282996)\n<total number of tokens: 1174866>\nrank orig_rank   type abs_freq nrm_freq\n---- --------- ------ -------- --------\n   1         1 the/at    68974  587.080\n   2         2    ,/,    58104  494.559\n   3         3    ./.    48774  415.145\n   4         4  of/in    35007  297.966\n   5         5 and/cc    28506  242.632\n   6         6   a/at    22915  195.044\n   7         7  in/in    20716  176.326\n```\n:::\n:::\n\n\n:::\n\n::::\n\n::: {.footer}\nHot example\n:::\n\n## Hot coffee\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap(hot_cooc, keep_re, \"^coffee/\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$target_freqlist\nFrequency list (types in list: 1, tokens in list: 4)\n<total number of tokens: 777>\nrank orig_rank      type abs_freq nrm_freq\n---- --------- --------- -------- --------\n   1        24 coffee/nn        4    51.48\n\n$ref_freqlist\nFrequency list (types in list: 2, tokens in list: 74)\n<total number of tokens: 1174866>\nrank orig_rank         type abs_freq nrm_freq\n---- --------- ------------ -------- --------\n   1      1450    coffee/nn       72    0.613\n   2     25804 coffee/nn-tl        2    0.017\n```\n:::\n:::\n\n\n::: {.footer}\nHot example\n:::\n\n\n\n\n# Observed frequencies\n\n## Important frequencies\n\n- Frequency of *hot/jj* context = $f(n)$ = 777^[Not the frequency of *hot/jj* (123).]\n- Frequency of *coffee/nn* = $f(c)$ = 76\n- Frequency of *coffee/nn* in the context of *hot/jj* = $f(n,c)$ = 4\n- Sum of the *hot/jj* context and not-*hot/jj* context = $N$ = 1175643\n\n::: {.footer}\nObserved frequencies\n:::\n\n## a, b, c, d...\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> Coffee </th>\n   <th style=\"text-align:left;\"> Not coffee </th>\n   <th style=\"text-align:left;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Context of <em>hot</em> </td>\n   <td style=\"text-align:left;\"> a </td>\n   <td style=\"text-align:left;\"> b </td>\n   <td style=\"text-align:left;\"> m = a + b </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Not context of <em>hot</em> </td>\n   <td style=\"text-align:left;\"> c </td>\n   <td style=\"text-align:left;\"> d </td>\n   <td style=\"text-align:left;\"> n = c + d </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Total </td>\n   <td style=\"text-align:left;\"> k = a + c </td>\n   <td style=\"text-align:left;\"> l = b + d </td>\n   <td style=\"text-align:left;\"> N = m + n </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: {.footer}\nObserved frequencies\n:::\n\n## O, R, C, N\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> Coffee </th>\n   <th style=\"text-align:left;\"> Not coffee </th>\n   <th style=\"text-align:left;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Context of <em>hot</em> </td>\n   <td style=\"text-align:left;\"> O<sub>11</sub> </td>\n   <td style=\"text-align:left;\"> O<sub>21</sub> </td>\n   <td style=\"text-align:left;\"> R<sub>1</sub> </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Not context of <em>hot</em> </td>\n   <td style=\"text-align:left;\"> O<sub>12</sub> </td>\n   <td style=\"text-align:left;\"> O<sub>22</sub> </td>\n   <td style=\"text-align:left;\"> R<sub>2</sub> </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Total </td>\n   <td style=\"text-align:left;\"> C<sub>1</sub> </td>\n   <td style=\"text-align:left;\"> C<sub>2</sub> </td>\n   <td style=\"text-align:left;\"> N </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: {.footer}\nObserved frequencies\n:::\n\n## Building the contingency table\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Coffee </th>\n   <th style=\"text-align:right;\"> Not coffee </th>\n   <th style=\"text-align:right;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Context of <em>hot</em> </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 773 </td>\n   <td style=\"text-align:right;\"> 777 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Not context of <em>hot</em> </td>\n   <td style=\"text-align:right;\"> 72 </td>\n   <td style=\"text-align:right;\"> 1 174 794 </td>\n   <td style=\"text-align:right;\"> 1 174 866 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Total </td>\n   <td style=\"text-align:right;\"> 76 </td>\n   <td style=\"text-align:right;\"> 1 175 567 </td>\n   <td style=\"text-align:right;\"> 1 175 643 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: {.incremental}\n- How important is it that *coffee* occurs 4 times in the context of *hot* when\n\n  + there are 773 other events in the context of *hot*\n  \n  + and *coffee* also occurs 72 times outside the context of *hot*?\n:::\n\n::: {.footer}\nObserved frequencies\n:::\n\n\n\n\n# Expected frequencies\n\n## Expected a, b, c, d...\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> Coffee </th>\n   <th style=\"text-align:left;\"> Not coffee </th>\n   <th style=\"text-align:left;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Context of <em>hot</em> </td>\n   <td style=\"text-align:left;\"> (m * k)/N </td>\n   <td style=\"text-align:left;\"> (m * l)/N </td>\n   <td style=\"text-align:left;\"> m </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Not context of <em>hot</em> </td>\n   <td style=\"text-align:left;\"> (n * k)/N </td>\n   <td style=\"text-align:left;\"> (n * l)/N </td>\n   <td style=\"text-align:left;\"> n </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Total </td>\n   <td style=\"text-align:left;\"> k </td>\n   <td style=\"text-align:left;\"> l </td>\n   <td style=\"text-align:left;\"> N </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: {.footer}\nExpected frequencies\n:::\n\n## E, R, C, N\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> Coffee </th>\n   <th style=\"text-align:left;\"> Not coffee </th>\n   <th style=\"text-align:left;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Context of <em>hot</em> </td>\n   <td style=\"text-align:left;\"> E<sub>11</sub> </td>\n   <td style=\"text-align:left;\"> E<sub>21</sub> </td>\n   <td style=\"text-align:left;\"> R<sub>1</sub> </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Not context of <em>hot</em> </td>\n   <td style=\"text-align:left;\"> E<sub>12</sub> </td>\n   <td style=\"text-align:left;\"> E<sub>22</sub> </td>\n   <td style=\"text-align:left;\"> R<sub>2</sub> </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Total </td>\n   <td style=\"text-align:left;\"> C<sub>1</sub> </td>\n   <td style=\"text-align:left;\"> C<sub>2</sub> </td>\n   <td style=\"text-align:left;\"> N </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: {.footer}\nExpected frequencies\n:::\n\n## Expected frequencies\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Coffee </th>\n   <th style=\"text-align:right;\"> Not coffee </th>\n   <th style=\"text-align:right;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Context of <em>hot</em> </td>\n   <td style=\"text-align:right;\"> 0.05 </td>\n   <td style=\"text-align:right;\"> 776.95 </td>\n   <td style=\"text-align:right;\"> 777 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Not context of <em>hot</em> </td>\n   <td style=\"text-align:right;\"> 75.95 </td>\n   <td style=\"text-align:right;\"> 1 174 790.05 </td>\n   <td style=\"text-align:right;\"> 1 174 866 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Total </td>\n   <td style=\"text-align:right;\"> 76.00 </td>\n   <td style=\"text-align:right;\"> 1 175 567.00 </td>\n   <td style=\"text-align:right;\"> 1 175 643 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: {.footer}\nExpected frequencies\n:::\n\n\n\n\n\n# Target and reference contexts\n\n## Contexts in the contingency table\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> Target item </th>\n   <th style=\"text-align:left;\"> Other items </th>\n   <th style=\"text-align:left;\"> Total </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Target context </td>\n   <td style=\"text-align:left;\"> O<sub>11</sub> </td>\n   <td style=\"text-align:left;\"> O<sub>21</sub> </td>\n   <td style=\"text-align:left;\"> R<sub>1</sub> </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Reference context </td>\n   <td style=\"text-align:left;\"> O<sub>12</sub> </td>\n   <td style=\"text-align:left;\"> O<sub>22</sub> </td>\n   <td style=\"text-align:left;\"> R<sub>2</sub> </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Total </td>\n   <td style=\"text-align:left;\"> C<sub>1</sub> </td>\n   <td style=\"text-align:left;\"> C<sub>2</sub> </td>\n   <td style=\"text-align:left;\"> N </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: {.footer}\nTarget and reference contexts\n:::\n\n## Collocation analysis\n\n- The **target** context is the surroundings of an item, the **node**, e.g. *hot*.\n\n  + In **surface collocations**, a certain window around the node, e.g. 3 tokens to either side.\n  \n  + In **textual collocations**, the text in which the node occurs.\n  \n  + In **syntactic collocations**, a certain syntactic relationship with the node.\n\n- The **reference** context is all the contexts **not** surrounding the node.\n\n::: {.footer}\nTarget and reference contexts\n:::\n\n## Distinctive collocation analysis\n\n- The **target** context is the surroundings of a node, e.g. *hot*.\n\n- The **reference** context is the surroundings of a second node for contrast, e.g. *cold*.\n\n::: callout-note\nIn (distinctive) collocation analysis, the \"target\" item is the **collocate**.\n:::\n\n::: {.footer}\nTarget and reference contexts\n:::\n\n## Keyword analysis\n\n- The **target** context is a text or corpus.\n\n- The **reference** context is another bigger, *reference* corpus.\n\n::: callout-note\nIn *Distinctive keyword analysis* the reference context is another target corpus.\n:::\n\n::: {.footer}\nTarget and reference contexts\n:::\n\n## Collostructional analysis\n\n- The **target** context is a certain slot in a construction.\n\n- The **reference** context is a comparable slot in a comparable construction.\n\n::: callout-note  \nWe talk about *distinctive collexeme analysis* when that second construction is very specific.\n:::\n\n::: {.footer}\nTarget and reference contexts\n:::\n\n\n\n\n\n# Summing up\n\n## Procedure\n\n1. For each type in the corpus, compute their frequencies in the target and reference contexts.\n\n2. We obtain two frequency lists from which we can obtain all necessary values of the contingency table.\n\n3. Based on the contingency tables, compute the association strength between each type and the target context.\n\n4. Rank and/or filter.\n\n::: {.footer}\nSumming up\n:::\n\n## Code\n\nMain function [`mclm::assoc_scores()`](https://masterclm.github.io/mclm/reference/assoc_scores.html).\n\n1. Obtain two frequency lists:\n\n- \"Manually\" (with `freqlist()` and different corpora, for example.)\n\n- With `surf_cooc()` for surface collocations.\n\n- With `text_cooc()` for textual collocations.\n\n2. Give the frequency lists to `assoc_scores()`.^[Alternatively, give the values of `a`, `b`, `c` and `d` to `assoc_abcd()`.]\n\n::: {.footer}\nSumming up\n:::\n\n## Hot example\n\n\n::: {.cell lable='assoc-hot'}\n\n```{.r .cell-code}\nassoc_scores(hot_cooc)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAssociation scores (types in list: 44)\n       type  a    PMI G_signed|  b     c       d dir  exp_a DP_rows\n 1      ,/, 49  0.350    2.824|728 58104 1116762   1 38.434   0.014\n 2   the/at 39 -0.226   -1.069|738 68974 1105892  -1 45.612  -0.009\n 3      ./. 38  0.236    1.010|739 48774 1126092   1 32.261   0.007\n 4   and/cc 36  0.932   12.660|741 28506 1146360   1 18.864   0.022\n 5     a/at 28  0.885    8.898|749 22915 1151951   1 15.163   0.017\n 6    of/in 21 -0.141   -0.213|756 35007 1139859  -1 23.151  -0.003\n 7    in/in 15  0.131    0.122|762 20716 1154150   1 13.701   0.002\n 8 was/bedz 13  1.004    5.120|764  9793 1165073   1  6.481   0.008\n 9 water/nn 13  5.529   74.799|764   413 1174453   1  0.282   0.016\n10  with/in 10  1.059    4.321|767  7251 1167615   1  4.799   0.007\n11   it/pps  9  1.218    4.975|768  5844 1169022   1  3.868   0.007\n12    to/to  8 -0.301   -0.380|769 14909 1159957  -1  9.859  -0.002\n13    on/in  7  0.795    1.796|770  6098 1168768   1  4.035   0.004\n14  cold/jj  6  6.029   38.634|771   133 1174733   1  0.092   0.008\n15    to/in  6 -0.283   -0.249|771 11040 1163826  -1  7.300  -0.002\n16    at/in  5  0.499    0.538|772  5348 1169518   1  3.538   0.002\n17  from/in  5  0.801    1.299|772  4337 1170529   1  2.870   0.003\n18   sun/nn  5  6.227   33.572|772    96 1174770   1  0.067   0.006\n19  this/dt  5  0.558    0.664|772  5133 1169733   1  3.396   0.002\n20           4 -1.166   -3.520|773 13577 1161289  -1  8.976  -0.006\n...\n<number of extra columns to the right: 7>\n```\n:::\n:::\n\n\n::: {.footer}\nSumming up\n:::\n\n\n## Hot-coffee association\n\n\n::: {.cell lable='assoc-hotcoffee'}\n\n```{.r .cell-code}\nassoc_scores(hot_cooc)[\"coffee/nn\",]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAssociation scores (types in list: 1)\n       type a   PMI G_signed|  b  c       d dir exp_a DP_rows RR_rows\n1 coffee/nn 4 6.315   27.349|773 72 1174794   1  0.05   0.005  84.003\n<number of extra columns to the right: 6>\n```\n:::\n:::\n\n\n::: {.footer}\nSumming up\n:::\n\n\n# Next: Association measures\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\r\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\r\n"
      ],
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n\r\n      // dispatch for htmlwidgets\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for reveal\r\n    if (window.Reveal) {\r\n      window.Reveal.addEventListener(\"slidechanged\", function(event) {\r\n        fireSlideChanged(event.previousSlide, event.currentSlide);\r\n      });\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}